### ISSUE TITLE
load nerfstudio model error

### ISSUE THREAD

**Issue by ja-yeon-kim** [cvachha/instruct-gs2gs#12]
Hello, I have an error like,

Loading latest Nerfstudio checkpoint from load_dir...
Traceback (most recent call last):
File "/home/anaconda3/envs/gs2gs/bin/ns-train", line 8, in
sys.exit(entrypoint())
File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
main(
File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 247, in main
launch(
File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 189, in launch
main_func(local_rank=0, world_size=world_size, config=config)
File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
trainer.setup()
File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 190, in setup
self._load_checkpoint()
File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 405, in _load_checkpoint
self.optimizers.load_optimizers(loaded_state["optimizers"])
File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/engine/optimizers.py", line 201, in load_optimizers
self.optimizers[k].load_state_dict(v)
KeyError: 'xyz'

I installed gsplat: 0.1.10, igs2gs: 0.1.0.
Thank you for helping with this issue.

**Comment by cvachha** [comment]
Hello, which version of Nerfstudio are you using? I recommend using the latest one from the nerfstudio main branch since there were some recent changes to splatfacto. Let me know if the error still appears.

**Comment by ja-yeon-kim** [comment]
Hello, Thank you for your reply.
Nerfstudio version is 1.0.3. 
I updated the version.
I keep experiencing the same error.

**Comment by cvachha** [comment]
I'm having trouble reproducing that error. On my system, it is working with the latest main branch of instruct-gs2gs and nerfstudio. Did you install nerfstudio from pip or from source from the main git branch?

**Comment by massyzs** [comment]
Also face this error.
