### ISSUE TITLE
Optimizer config for 'means' not found in config file

### ISSUE THREAD

**Issue by RaemyS** [cvachha/instruct-gs2gs#8]
Hi,

I recently started exploring Gaussian Splatting in nerfstudio. I came across your Instruct-GS2GS and wanted to play around with it a bit.

When running ns-train with igs2gs, I get the following error message after loading the pipeline components:

-------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/user/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/user/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/user/nerfstudio/nerfstudio/engine/trainer.py", line 156, in setup
    self.optimizers = self.setup_optimizers()
  File "/home/user/nerfstudio/nerfstudio/engine/trainer.py", line 222, in setup_optimizers
    return Optimizers(optimizer_config, param_groups)
  File "/home/user/nerfstudio/nerfstudio/engine/optimizers.py", line 103, in __init__
    raise RuntimeError(
RuntimeError: Optimizer config for 'means' not found in config file. Make sure you specify an optimizer for each parameter group. Provided configs were: dict_keys(['xyz', 'features_dc', 'features_rest', 'opacity', 'scaling', 'rotation', 'camera_opt'])
-------------------------------------------------------------------------------------------------------------------------------------------------

With ns-train igs2gs --help I find some blocks for the optimizers (xyz, opacity, ...) but none for "means". Could the problem be due to my setup or is this perhaps a bug?

I work with a locally built Docker container. The code is based on commit 8e0c6875 from last week from the main branch of the nerfstudio repository.

Thank you for having a look at this :)

**Comment by gmcarmen** [comment]
I met the same question

**Comment by chensh1127** [comment]
I met the same issues....

**Comment by m-mousatat** [comment]
same problem

**Comment by cvachha** [comment]
Thanks for informing us of this. I found the issue and will update a fix for this later today.

**Comment by Mousatat** [comment]
Thanks a lot, I cannot wait to try it again.😁

**Comment by cvachha** [comment]
Just pushed the update. Let me know if you run into any other issues.

**Comment by RaemyS** [comment]
seems to work now, thanks for the fix👍

**Comment by ja-yeon-kim** [comment]
Hello, I have an error like,  

Loading latest Nerfstudio checkpoint from load_dir...
Traceback (most recent call last):
  File "/home/anaconda3/envs/gs2gs/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 190, in setup
    self._load_checkpoint()
  File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 405, in _load_checkpoint
    self.optimizers.load_optimizers(loaded_state["optimizers"])
  File "/home/anaconda3/envs/gs2gs/lib/python3.9/site-packages/nerfstudio/engine/optimizers.py", line 201, in load_optimizers
    self.optimizers[k].load_state_dict(v)
KeyError: 'xyz'

**Comment by MrHenderson6** [comment]
I encountered the same issue, but I wasn't using your project. I was simply trying to train the `ros-depth-splatfacto` model on the `desk` scene provided by NeRFBridge for testing, and this error occurred. Do you know how to fix this problem?
RuntimeError: Optimizer config for 'means' not found in config file. Make sure you specify an optimizer for each parameter group. Provided configs were: dict_keys(['xyz', 'features_dc', 'features_rest', 'opacity', 'scaling', 'rotation', 'camera_opt'])
